version: "3.8"

services:
  product-service:
    build:
      context: .
      dockerfile: product/Dockerfile
    ports:
      - "8081:8080"
    environment:
      SPRING_PROFILES_ACTIVE: dev
    depends_on:
      - mysql

  order-service:
    build:
      context: .
      dockerfile: order/Dockerfile
    ports:
      - "8082:8080"
    environment:
      SPRING_PROFILES_ACTIVE: dev
    depends_on:
      - mysql

  member-service:
    build:
      context: .
      dockerfile: member/Dockerfile
    ports:
      - "8083:8080"
    environment:
      SPRING_PROFILES_ACTIVE: dev
    depends_on:
      - mysql

  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: ecommerce
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
